# Generated by Django 3.0.5 on 2020-12-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='mensagm',
            new_name='mensagem',
        ),
    ]
