# Generated by Django 3.0.5 on 2020-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20201203_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='respondido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
